Homework 2
================
Alisha Sarakki

``` r
library(tidyverse)
```

    ## ── Attaching packages ───────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ──────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
library(dplyr)
tibble()
```

    ## # A tibble: 0 x 0

## Problem 1

Read the Mr. Trash-Wheel dataset.

``` r
trashwheel_df = 
  read_xlsx(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "Mr. Trash Wheel",
    range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  ) 
```

Read precipitation data\!

``` r
precip_2018 =
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    skip = 1
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018) %>% 
  relocate(year)
```

``` r
precip_2017 =
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    skip = 1
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```

Now combine annual precipitation.

``` r
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

precip_df =
  bind_rows(precip_2018, precip_2017)
  
left_join(precip_df, month_df, by = "month")
```

    ## # A tibble: 24 x 4
    ##     year month total month_name
    ##    <dbl> <dbl> <dbl> <chr>     
    ##  1  2018     1  0.94 January   
    ##  2  2018     2  4.8  February  
    ##  3  2018     3  2.69 March     
    ##  4  2018     4  4.69 April     
    ##  5  2018     5  9.27 May       
    ##  6  2018     6  4.77 June      
    ##  7  2018     7 10.2  July      
    ##  8  2018     8  6.45 August    
    ##  9  2018     9 10.5  September 
    ## 10  2018    10  2.12 October   
    ## # … with 14 more rows

This dataset contains information from the Mr. Trashwheel trash
collector in Baltimore, MD. As the trash enters the inner harbor, the
trashwheel collects that trash adn stores it in a dumpster. The dataset
contains information on year, month, trash collected, and specific types
of trash. There are a total of ‘r nrow(trashwheel\_df)’ rows in our
final dataset. Additional data sheets include month precipitation data.

## Problem 2

Import and clean NYC transit data

``` r
NYCTransit_data = 
  read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
  names(NYCTransit_data)
```

    ##  [1] "Division"           "Line"               "Station Name"      
    ##  [4] "Station Latitude"   "Station Longitude"  "Route1"            
    ##  [7] "Route2"             "Route3"             "Route4"            
    ## [10] "Route5"             "Route6"             "Route7"            
    ## [13] "Route8"             "Route9"             "Route10"           
    ## [16] "Route11"            "Entrance Type"      "Entry"             
    ## [19] "Exit Only"          "Vending"            "Staffing"          
    ## [22] "Staff Hours"        "ADA"                "ADA Notes"         
    ## [25] "Free Crossover"     "North South Street" "East West Street"  
    ## [28] "Corner"             "Entrance Latitude"  "Entrance Longitude"
    ## [31] "Station Location"   "Entrance Location"

``` r
  NYCTransit_data = janitor::clean_names(NYCTransit_data)
  names(NYCTransit_data)
```

    ##  [1] "division"           "line"               "station_name"      
    ##  [4] "station_latitude"   "station_longitude"  "route1"            
    ##  [7] "route2"             "route3"             "route4"            
    ## [10] "route5"             "route6"             "route7"            
    ## [13] "route8"             "route9"             "route10"           
    ## [16] "route11"            "entrance_type"      "entry"             
    ## [19] "exit_only"          "vending"            "staffing"          
    ## [22] "staff_hours"        "ada"                "ada_notes"         
    ## [25] "free_crossover"     "north_south_street" "east_west_street"  
    ## [28] "corner"             "entrance_latitude"  "entrance_longitude"
    ## [31] "station_location"   "entrance_location"

Specify which columns to keep

``` r
NYCT1_data = 
  select(NYCTransit_data, line:entry, vending, ada)
```

Character to Logical Expression Conversion

``` r
NYCT1_data %>% 
  mutate(entry = recode(entry, YES = "TRUE", NO = "FALSE"))
```

    ## # A tibble: 1,868 x 19
    ##    line  station_name station_latitude station_longitu… route1 route2 route3
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Av… 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ##  2 4 Av… 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ##  3 4 Av… 36th St                  40.7            -74.0 N      R      <NA>  
    ##  4 4 Av… 36th St                  40.7            -74.0 N      R      <NA>  
    ##  5 4 Av… 36th St                  40.7            -74.0 N      R      <NA>  
    ##  6 4 Av… 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  7 4 Av… 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  8 4 Av… 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  9 4 Av… 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ## 10 4 Av… 53rd St                  40.6            -74.0 R      <NA>   <NA>  
    ## # … with 1,858 more rows, and 12 more variables: route4 <chr>, route5 <chr>,
    ## #   route6 <chr>, route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entrance_type <chr>, entry <chr>, vending <chr>, ada <lgl>

This dataset describes information about each entrance and exit for all
subway stations in New York, including, broadly, detailed location of
both station and entrance/exit, station name, which routes they lie on,
descriptions of entrances (stairs/escalator/etc.), and ADA compliance.
Thus far, I have narrowed the scope of this data to include line,
latitude and longitude, station name, train routes, entrance type, and
whether the station is ADA compliant. I have also cleaned the names of
the dataset, and converted the entry expression of “YES/NO” to a logical
expression of “TRUE/FALSE”.The dimensions are 1868 x 19.These data are
not tidy.

Distinct Stations

``` r
  distinct(NYCT1_data, station_name, line)
```

    ## # A tibble: 465 x 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # … with 455 more rows

``` r
count(distinct(NYCT1_data, station_name, line))
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   465

465 total distinct stations

ADA Compliant Stations

``` r
filter(NYCT1_data, ada == TRUE) %>% 
distinct(line, station_name) %>%
count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    84

84 stations are ADA compliant.

Proportion of station entrances/exits without vending that allow
entrance

``` r
NYCT1_data %>% 
  mutate(entry = recode(entry, YES = "TRUE", NO = "FALSE")) %>% 
filter(vending == "NO", entry == "TRUE") %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    69

``` r
NYCT1_data %>% 
  mutate(entry = recode(entry, YES = "TRUE", NO = "FALSE")) %>% 
filter(vending =="NO") %>% 
count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   183

``` r
69/183
```

    ## [1] 0.3770492

69 total station entries and exits without vending that allow entrance
183 total station entries and exits without vending Final proportion:
0.3770492

Reformat route number and route name

``` r
NYCT_tidy =
  NYCT1_data%>%
  mutate_at(vars(route1:route11), as.character) %>%
  pivot_longer(
    route1:route11,
    names_to = "route_no",
    values_to = "route_name",
    names_prefix = "route",
  )
```

Distinct Stations Serving A train

``` r
filter(NYCT_tidy, route_name == "A" ) %>% 
distinct(line, station_name)
```

    ## # A tibble: 60 x 2
    ##    line            station_name                 
    ##    <chr>           <chr>                        
    ##  1 42nd St Shuttle Times Square                 
    ##  2 8 Avenue        125th St                     
    ##  3 8 Avenue        145th St                     
    ##  4 8 Avenue        14th St                      
    ##  5 8 Avenue        168th St - Washington Heights
    ##  6 8 Avenue        175th St                     
    ##  7 8 Avenue        181st St                     
    ##  8 8 Avenue        190th St                     
    ##  9 8 Avenue        34th St                      
    ## 10 8 Avenue        42nd St                      
    ## # … with 50 more rows

There are 20548 distinct stations that serve the A line.

``` r
filter(NYCT_tidy, route_name == "A", ada == TRUE) %>% 
distinct(line, station_name) %>%
count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    17

Of all distinct stations that serve the A, 17 are ADA compliant.

## Problem 3

Import 538 data

``` r
pols_data = 
  read_csv(file = "./data/pols-month.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

``` r
snp_data = 
  read_csv(file = "./data/snp.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   date = col_character(),
    ##   close = col_double()
    ## )

``` r
unemployment_data = 
    read_csv(file = "./data/unemployment.csv" )
```

    ## Parsed with column specification:
    ## cols(
    ##   Year = col_double(),
    ##   Jan = col_double(),
    ##   Feb = col_double(),
    ##   Mar = col_double(),
    ##   Apr = col_double(),
    ##   May = col_double(),
    ##   Jun = col_double(),
    ##   Jul = col_double(),
    ##   Aug = col_double(),
    ##   Sep = col_double(),
    ##   Oct = col_double(),
    ##   Nov = col_double(),
    ##   Dec = col_double()
    ## )

Clean pols-month data

``` r
clean_pols = 
  pols_data %>% 
  separate("mon", into = c("year", "month", "day")) %>% 
  mutate(month = as.numeric(month))

month_pols = 
  tibble( 
   month = (1:12),
    month_name = month.name) %>% 
    mutate(months = as.numeric(month))

clean_month_pols = left_join(clean_pols, month_pols, by = "month")

clean_month_pols %>% 
  mutate(president = case_when(
    prez_gop == 1 ~ "gop",
    prez_dem == 1 ~ "dem")) %>% 
    select(-prez_gop, -prez_dem, -month, -day)
```

    ## # A tibble: 822 x 10
    ##    year  gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem month_name months
    ##    <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>       <dbl>
    ##  1 1947       23      51     253      23      45     198 January         1
    ##  2 1947       23      51     253      23      45     198 February        2
    ##  3 1947       23      51     253      23      45     198 March           3
    ##  4 1947       23      51     253      23      45     198 April           4
    ##  5 1947       23      51     253      23      45     198 May             5
    ##  6 1947       23      51     253      23      45     198 June            6
    ##  7 1947       23      51     253      23      45     198 July            7
    ##  8 1947       23      51     253      23      45     198 August          8
    ##  9 1947       23      51     253      23      45     198 September       9
    ## 10 1947       23      51     253      23      45     198 October        10
    ## # … with 812 more rows, and 1 more variable: president <chr>

``` r
head(arrange(clean_month_pols, year, month_name))
```

    ## # A tibble: 6 x 13
    ##   year  month day   prez_gop gov_gop sen_gop rep_gop prez_dem gov_dem sen_dem
    ##   <chr> <dbl> <chr>    <dbl>   <dbl>   <dbl>   <dbl>    <dbl>   <dbl>   <dbl>
    ## 1 1947      4 15           0      23      51     253        1      23      45
    ## 2 1947      8 15           0      23      51     253        1      23      45
    ## 3 1947     12 15           0      24      51     253        1      23      45
    ## 4 1947      2 15           0      23      51     253        1      23      45
    ## 5 1947      1 15           0      23      51     253        1      23      45
    ## 6 1947      7 15           0      23      51     253        1      23      45
    ## # … with 3 more variables: rep_dem <dbl>, month_name <chr>, months <dbl>

``` r
intermed_pols_ = 
  clean_month_pols %>% 
  mutate(year = as.numeric(year))
```

snp cleaning + tidying

``` r
clean_snp = 
  snp_data %>% 
  separate("date", into = c("month", "day", "year")) %>% 
  mutate(month = as.numeric(month))

month_snp = 
  tibble( 
   month = (1:12),
    month_name = month.name) %>% 
    mutate(month = as.numeric(month))

clean_month_snp = left_join(clean_snp, month_snp, by = "month")

clean_month_snp %>% 
  relocate(year, month)
```

    ## # A tibble: 787 x 5
    ##    year  month day   close month_name
    ##    <chr> <dbl> <chr> <dbl> <chr>     
    ##  1 2015      7 1     2080. July      
    ##  2 2015      6 1     2063. June      
    ##  3 2015      5 1     2107. May       
    ##  4 2015      4 1     2086. April     
    ##  5 2015      3 2     2068. March     
    ##  6 2015      2 2     2104. February  
    ##  7 2015      1 2     1995. January   
    ##  8 2014     12 1     2059. December  
    ##  9 2014     11 3     2068. November  
    ## 10 2014     10 1     2018. October   
    ## # … with 777 more rows

``` r
intermed_snp = 
  clean_month_snp %>% 
  mutate(year = as.numeric(year))
```

Tidy unemployment data

``` r
clean_unemp = 
  unemployment_data %>% 
  janitor::clean_names() %>% 
 pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percent unemployed"
 ) %>% 
   mutate(month = as.numeric(month))
```

    ## Warning: Problem with `mutate()` input `month`.
    ## ℹ NAs introduced by coercion
    ## ℹ Input `month` is `as.numeric(month)`.

    ## Warning in mask$eval_all_mutate(dots[[i]]): NAs introduced by coercion

``` r
intermed_unemploy = 
  clean_unemp %>% 
  mutate((month = recode(month, jan = "january", feb = "february", mar = "march", apr = "april", may = "may", jun = "june", jul = "july", aug = "august", sep = "september", oct = "october", nov = "november", dec = "december")))
```

    ## Warning: Problem with `mutate()` input `..1`.
    ## ℹ NAs introduced by coercion
    ## ℹ Input `..1` is `(...)`.

    ## Warning in recode.numeric(month, jan = "january", feb = "february", mar =
    ## "march", : NAs introduced by coercion

``` r
intermed_unemploy_2 = 
  clean_unemp %>% 
  mutate(year = as.numeric(year))

month_unemp = 
  tibble( 
   month = (1:12),
    month_name = month.name) %>% 
    mutate("month" = as.numeric(month))

final_unemploy =
  left_join(intermed_unemploy, month_unemp)
```

    ## Joining, by = "month"

Joining datasets

``` r
pols_snp = 
  left_join(intermed_pols_, intermed_snp)
```

    ## Joining, by = c("year", "month", "day", "month_name")

``` r
final_join =  
  left_join(pols_snp, intermed_unemploy)
```

    ## Joining, by = c("year", "month")

``` r
final_join
```

    ## # A tibble: 822 x 16
    ##     year month day   prez_gop gov_gop sen_gop rep_gop prez_dem gov_dem sen_dem
    ##    <dbl> <dbl> <chr>    <dbl>   <dbl>   <dbl>   <dbl>    <dbl>   <dbl>   <dbl>
    ##  1  1947     1 15           0      23      51     253        1      23      45
    ##  2  1947     2 15           0      23      51     253        1      23      45
    ##  3  1947     3 15           0      23      51     253        1      23      45
    ##  4  1947     4 15           0      23      51     253        1      23      45
    ##  5  1947     5 15           0      23      51     253        1      23      45
    ##  6  1947     6 15           0      23      51     253        1      23      45
    ##  7  1947     7 15           0      23      51     253        1      23      45
    ##  8  1947     8 15           0      23      51     253        1      23      45
    ##  9  1947     9 15           0      23      51     253        1      23      45
    ## 10  1947    10 15           0      23      51     253        1      23      45
    ## # … with 812 more rows, and 6 more variables: rep_dem <dbl>, month_name <chr>,
    ## #   months <dbl>, close <dbl>, `percent unemployed` <dbl>, `(...)` <chr>

Explain briefly what each dataset contained, and describe the resulting
dataset (e.g. give the dimension, range of years, and names of key
variables

These data describe the number of national politicians that are
democratic or republican at any given time, data pertaining to the stock
market (S\&P index), and percentage/proportion of unemployment at a
given time. The dimensions are 822 x 16. The range of years is between
NA and NA. Key variables include governor/senator and presidential
political affiliation, as related to time.
